
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace oplan
{

using System;
    using System.Collections.Generic;
    
public partial class oprema
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public oprema()
    {

        this.postrojba = new HashSet<postrojba>();

    }


    public int id_oprema { get; set; }

    public string model { get; set; }

    public string opis { get; set; }

    public int id_tip_oprema { get; set; }

    public int id_zemlja { get; set; }



    public virtual tip_opreme tip_opreme { get; set; }

    public virtual zemlja zemlja { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<postrojba> postrojba { get; set; }

}

}
