//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class postrojba
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public postrojba()
        {
            this.ruta = new HashSet<ruta>();
        }
    
        public int id_postrojba { get; set; }
        public double izdrzljivost { get; set; }
        public double brzina { get; set; }
        public int id_vrsta { get; set; }
        public int id_tip { get; set; }
    
        public virtual tip tip { get; set; }
        public virtual vrsta vrsta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ruta> ruta { get; set; }
    }
}
