
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace oplan
{

using System;
    using System.Collections.Generic;
    
public partial class promjena
{

    public int id_plan { get; set; }

    public int id_korisnik { get; set; }

    public System.DateTime datum { get; set; }

    public string radnja { get; set; }



    public virtual korisnik korisnik { get; set; }

    public virtual plan plan { get; set; }

}

}
