
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace oplan
{

using System;
    using System.Collections.Generic;
    
public partial class tocka
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tocka()
    {

        this.tocka1 = new HashSet<tocka>();

    }


    public int id_tocka { get; set; }

    public decimal koord_x { get; set; }

    public decimal koord_y { get; set; }

    public string marker { get; set; }

    public Nullable<int> zavrsna { get; set; }

    public int id_plan { get; set; }

    public int id_postrojba { get; set; }

    public int id_pripadnost { get; set; }



    public virtual plan plan { get; set; }

    public virtual postrojba postrojba { get; set; }

    public virtual pripadnost pripadnost { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tocka> tocka1 { get; set; }

    public virtual tocka tocka2 { get; set; }

}

}
