//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace oplan
{
    using System;
    using System.Collections.Generic;
    
    public partial class vrsta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vrsta()
        {
            this.postrojba = new HashSet<postrojba>();
        }
    
        public int id_vrsta { get; set; }
        public string naziv { get; set; }
        public string opis { get; set; }
        public string oznaka { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<postrojba> postrojba { get; set; }
    }
}
